name: Deploy a Client Site

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev or prod)"
        required: true
        type: environment

      client:
        description: "Client folder (e.g. example-client)"
        required: true
        type: choice
        options:
          - example-client
          - clfitness

jobs:
  echo-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Terraform inputs
        run: |
          echo "=============================="
          echo "====   Deployment Inputs   ==="
          echo "=============================="

          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Client: ${{ github.event.inputs.client }}"
          echo "=============================="


  run-terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read

    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      WORKING_DIR: terraform/clients/${{ github.event.inputs.client }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # --- Python Setup ---
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Build lambda packages
        run: |
          chmod +x scripts/build_lambdas.sh
          ./scripts/build_lambdas.sh

      # --- AWS AUTH ---
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      # --- Upload Lambda Artifacts ---
      - name: Upload Lambda artifacts to S3
        run: |
          ARTIFACT_BUCKET=${{ github.event.inputs.environment }}-wds-lambda-artifacts
          ARTIFACT_PREFIX=${{ github.event.inputs.client }}

          echo "Uploading to s3://$ARTIFACT_BUCKET/$ARTIFACT_PREFIX/"

          aws s3 cp build/ s3://$ARTIFACT_BUCKET/$ARTIFACT_PREFIX/ --recursive --exclude "*" --include "*.zip"

      # --- Upload Resources ---
      - name: Upload resources to S3
        run: |
          RESOURCES_BUCKET=${{ github.event.inputs.environment }}-wds-resources
          CLIENT_DIR=${{ github.event.inputs.client }}

          echo "Uploading to s3://$RESOURCES_BUCKET/$CLIENT_DIR/"

          aws s3 sync resources/$CLIENT_DIR s3://$RESOURCES_BUCKET/$CLIENT_DIR/

      # --- Terraform Setup ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          terraform init \
            -backend-config=backend_config/${{ github.event.inputs.environment }}.conf

      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          terraform plan \
            -var-file=tfvars/${{ github.event.inputs.environment }}.tfvars \
            -var="github_workspace=${{ github.workspace }}"

      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          terraform apply -auto-approve \
            -var-file=tfvars/${{ github.event.inputs.environment }}.tfvars \
            -var="github_workspace=${{ github.workspace }}"